default_install_hook_types:
  - pre-commit
  - pre-push
repos: []
#  - repo: https://github.com/gruntwork-io/pre-commit
#    rev: v0.1.28
#    hooks:
#      - id: helmlint
#        args:
#          - --with-subcharts
#          - --strict
#          - --debug
#        stages:
#          - manual
#          - pre-commit
#          - pre-push
#  - repo: https://github.com/jtyr/kubeconform-helm
#    rev: v0.1.16
#    hooks:
#      - id: kubeconform-helm
#        files: ^(helper-|)apps/[^/]+/(\.kubeconform|\.helmignore|templates/NOTES.txt|.*\.(ya?ml|json|tpl))$
#        args:
#          - --summary
#          - --verbose
#        stages:
#          - manual
#          - pre-commit
#          - pre-push
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v3.4.0
#    hooks:
#      - id: check-json
#      - id: check-yaml
#      - id: trailing-whitespace
#      - id: end-of-file-fixer
#  - repo: https://github.com/adrienverge/yamllint.git
#    rev: v1.37.0
#    hooks:
#      - id: yamllint
#        args:
#          - --strict
#        stages:
#          - manual
#          - pre-commit
#          - pre-push
