apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-streaming-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/hajlesilesia
      targetRevision: 1.0.0
      chart: event-streaming-ui-config
  destination:
    server: '{{ .Values.spec.destination.server }}'
    namespace: event-streaming
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
