apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-content-query
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/hajlesilesia
      targetRevision: 1.1.5
      path: helm
      chart: file-content-query-config
  destination:
    server: '{{ .Values.spec.destination.server }}'
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
