apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msg-queuing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/hajlesilesia
      targetRevision: 1.1.7
      chart: msg-queuing-config
  destination:
    server: '{{ .Values.spec.destination.server }}'
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
