apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/hajle-silesia/container-orchestration-cd.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{index .path.segments 1}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: "app=hajlesilesia/{{index .path.segments 1}}"
        argocd-image-updater.argoproj.io/write-back-method: git:secret:image-updater/image-updater
        argocd-image-updater.argoproj.io/write-back-target: helmvalues
        argocd-image-updater.argoproj.io/git-repository: git@github.com:hajle-silesia/container-orchestration-cd.git
        argocd-image-updater.argoproj.io/app.helm.image-name: app.image.repository
        argocd-image-updater.argoproj.io/app.helm.image-tag: app.image.tag
    spec:
      project: default
      source:
        repoURL: https://github.com/hajle-silesia/container-orchestration-cd.git
        targetRevision: master
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
