name: CI

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests-and-static-analysis:
    name: Tests and static analysis
    uses: hajle-silesia/.github/.github/workflows/shared-tests-and-static-analysis.yaml@v2.6.3

#  chart-package:
#    name: Chart package
#    uses: hajle-silesia/.github/.github/workflows/shared-chart-package.yaml@v2.3.3
#    with:
#      docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
#      docker-hub-namespace: ${{ vars.DOCKER_HUB_NAMESPACE }}
#      dir: charts/hajle-silesia
#    secrets:
#      docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
