apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "helm.fullname" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-store
    kind: ClusterSecretStore
  target:
    name: {{ include "helm.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: image-updater
        property: sshPrivateKey
