apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: image-updater
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-store
    kind: ClusterSecretStore
  target:
    name: image-updater
    creationPolicy: Owner
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: image-updater
        property: sshPrivateKey
